server:
  port: 0
spring:
  application:
    name: HAPPY-VERPACKUNG-SERVICE

  kafka:
    #properties:
     # sasl:
      #  jaas:
       #   config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
       # mechanism: PLAIN
      # security:
       # protocol: SASL_PLAINTEXT
    topic:
      name: verpackung-topic
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      auto-offset-reset: earliest
      # client-id: verpackung
      group-id: myGroup

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
          spring:
            deserializer:
              value:
                delegate:
                  class: org.springframework.kafka.support.serializer.JsonDeserializer
            json:
              trusted:
                packages: at.happy.*
      # max-poll-records: 1




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

